"""
Stock lists, ETF info, and configuration for NiveshAI
"""

# Top NIFTY 50 stocks (Large Cap) - Yahoo Finance uses .NS suffix for NSE
NIFTY_50 = {
    "RELIANCE.NS": "Reliance Industries",
    "TCS.NS": "Tata Consultancy Services",
    "HDFCBANK.NS": "HDFC Bank",
    "INFY.NS": "Infosys",
    "ICICIBANK.NS": "ICICI Bank",
    "HINDUNILVR.NS": "Hindustan Unilever",
    "ITC.NS": "ITC Limited",
    "SBIN.NS": "State Bank of India",
    "BHARTIARTL.NS": "Bharti Airtel",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "LT.NS": "Larsen & Toubro",
    "AXISBANK.NS": "Axis Bank",
    "ASIANPAINT.NS": "Asian Paints",
    "MARUTI.NS": "Maruti Suzuki",
    "HCLTECH.NS": "HCL Technologies",
    "SUNPHARMA.NS": "Sun Pharma",
    "TITAN.NS": "Titan Company",
    "BAJFINANCE.NS": "Bajaj Finance",
    "WIPRO.NS": "Wipro",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "NESTLEIND.NS": "Nestle India",
    "POWERGRID.NS": "Power Grid Corp",
    "NTPC.NS": "NTPC Limited",
    "TATAMOTORS.NS": "Tata Motors",
    "JSWSTEEL.NS": "JSW Steel",
    "ONGC.NS": "ONGC",
    "COALINDIA.NS": "Coal India",
    "TECHM.NS": "Tech Mahindra",
    "INDUSINDBK.NS": "IndusInd Bank",
    "CIPLA.NS": "Cipla",
    "DRREDDY.NS": "Dr. Reddy's Labs",
    "EICHERMOT.NS": "Eicher Motors",
    "GRASIM.NS": "Grasim Industries",
    "DIVISLAB.NS": "Divi's Laboratories",
    "BPCL.NS": "BPCL",
    "APOLLOHOSP.NS": "Apollo Hospitals",
    "HEROMOTOCO.NS": "Hero MotoCorp",
    "BRITANNIA.NS": "Britannia Industries",
    "TATACONSUM.NS": "Tata Consumer Products",
    "HINDALCO.NS": "Hindalco Industries",
    "M&M.NS": "Mahindra & Mahindra",
    "BAJAJ-AUTO.NS": "Bajaj Auto",
    "LTIM.NS": "LTIMindtree",
    "TATASTEEL.NS": "Tata Steel",
    "ADANIENT.NS": "Adani Enterprises",
    "ADANIPORTS.NS": "Adani Ports",
    "BAJAJFINSV.NS": "Bajaj Finserv",
    "SBILIFE.NS": "SBI Life Insurance",
    "HDFCLIFE.NS": "HDFC Life Insurance",
}

# NIFTY NEXT 50 stocks (Mid Cap)
NIFTY_NEXT_50 = {
    "SIEMENS.NS": "Siemens India",
    "HAL.NS": "Hindustan Aeronautics",
    "DLF.NS": "DLF Limited",
    "ABB.NS": "ABB India",
    "BANKBARODA.NS": "Bank of Baroda",
    "PNB.NS": "Punjab National Bank",
    "INDIGO.NS": "InterGlobe Aviation",
    "GODREJCP.NS": "Godrej Consumer",
    "HAVELLS.NS": "Havells India",
    "PIDILITIND.NS": "Pidilite Industries",
    "DABUR.NS": "Dabur India",
    "AMBUJACEM.NS": "Ambuja Cements",
    "SHREECEM.NS": "Shree Cement",
    "TRENT.NS": "Trent Limited",
    "VEDL.NS": "Vedanta Limited",
    "IOC.NS": "Indian Oil Corp",
    "GAIL.NS": "GAIL India",
    "MARICO.NS": "Marico Limited",
    "COLPAL.NS": "Colgate-Palmolive India",
    "BERGEPAINT.NS": "Berger Paints",
    "JUBLFOOD.NS": "Jubilant FoodWorks",
    "MUTHOOTFIN.NS": "Muthoot Finance",
    "LUPIN.NS": "Lupin Limited",
    "TORNTPHARM.NS": "Torrent Pharma",
    "AUROPHARMA.NS": "Aurobindo Pharma",
    "CANBK.NS": "Canara Bank",
    "IDFCFIRSTB.NS": "IDFC First Bank",
    "PFC.NS": "Power Finance Corp",
    "RECLTD.NS": "REC Limited",
    "IRCTC.NS": "IRCTC",
}

# Popular Indian ETFs
ETFS = {
    "NIFTYBEES.NS": {
        "name": "Nippon India Nifty 50 BeES",
        "tracks": "NIFTY 50",
        "category": "Large Cap",
        "expense_ratio": "0.04%",
        "description": "Tracks the NIFTY 50 index — India's top 50 companies by market cap.",
        "strengths": [
            "Lowest expense ratio among Nifty ETFs",
            "Most liquid ETF in India — tight bid-ask spread",
            "Instant diversification across 50 blue-chip stocks",
            "Ideal for beginners and SIP investors",
        ],
        "weaknesses": [
            "Limited to large-cap — misses mid/small-cap growth",
            "Top-heavy: top 10 stocks make up ~60% weight",
            "Returns capped by large-cap nature (~12-14% CAGR historically)",
        ],
    },
    "JUNIORBEES.NS": {
        "name": "Nippon India Nifty Next 50 Junior BeES",
        "tracks": "NIFTY NEXT 50",
        "category": "Mid Cap",
        "expense_ratio": "0.15%",
        "description": "Tracks the NIFTY Next 50 index — stocks ranked 51-100 by market cap.",
        "strengths": [
            "Higher growth potential than Nifty 50",
            "Contains future Nifty 50 candidates",
            "Good diversification across sectors",
            "Better returns historically in bull markets",
        ],
        "weaknesses": [
            "Higher volatility than Nifty 50 ETF",
            "Higher expense ratio than NIFTYBEES",
            "Less liquidity — wider bid-ask spread",
            "Bigger drawdowns in market crashes",
        ],
    },
    "BANKBEES.NS": {
        "name": "Nippon India Bank BeES",
        "tracks": "NIFTY Bank",
        "category": "Sectoral",
        "expense_ratio": "0.19%",
        "description": "Tracks the Bank Nifty index — India's top banking stocks.",
        "strengths": [
            "Concentrated exposure to India's banking growth story",
            "High liquidity among sectoral ETFs",
            "Banks benefit from India's credit growth cycle",
        ],
        "weaknesses": [
            "No diversification — 100% banking sector",
            "Highly sensitive to RBI policy and NPA cycles",
            "Can underperform badly during banking crises",
        ],
    },
    "GOLDBEES.NS": {
        "name": "Nippon India Gold BeES",
        "tracks": "Gold Price",
        "category": "Commodity",
        "expense_ratio": "0.79%",
        "description": "Tracks domestic gold prices. A hedge against inflation and market crashes.",
        "strengths": [
            "Safe haven during market downturns",
            "Hedge against inflation and rupee depreciation",
            "No storage hassle vs physical gold",
            "Cultural relevance — Indians love gold",
        ],
        "weaknesses": [
            "Highest expense ratio among listed ETFs",
            "No dividends or earnings growth",
            "Can underperform equities in bull markets for years",
            "Tracking error can be higher",
        ],
    },
}

# Risk profile allocation suggestions (percentages)
ALLOCATION = {
    "conservative": {
        "label": "Conservative",
        "description": "You prefer safety over returns. Capital preservation is your priority.",
        "allocation": {
            "Nifty 50 ETF (Large Cap)": 50,
            "Gold ETF": 20,
            "Nifty Next 50 ETF (Mid Cap)": 15,
            "Bank ETF (Sectoral)": 15,
        },
        "monthly_note": "Start with a monthly SIP of any amount you're comfortable with. Even Rs.500/month in a Nifty 50 ETF builds wealth over time.",
    },
    "moderate": {
        "label": "Moderate",
        "description": "You want growth but can handle some ups and downs.",
        "allocation": {
            "Nifty 50 ETF (Large Cap)": 40,
            "Nifty Next 50 ETF (Mid Cap)": 25,
            "Individual Large Cap Stocks": 15,
            "Bank ETF (Sectoral)": 10,
            "Gold ETF": 10,
        },
        "monthly_note": "A balanced approach. Use ETFs as your core (65%) and pick individual stocks for the rest. Review quarterly.",
    },
    "aggressive": {
        "label": "Aggressive",
        "description": "You're comfortable with high volatility for potentially higher returns.",
        "allocation": {
            "Nifty 50 ETF (Large Cap)": 25,
            "Nifty Next 50 ETF (Mid Cap)": 25,
            "Individual Large Cap Stocks": 20,
            "Individual Mid Cap Stocks": 15,
            "Bank ETF (Sectoral)": 10,
            "Gold ETF": 5,
        },
        "monthly_note": "Higher risk, higher potential. Keep at least 50% in ETFs as a safety net. Don't chase penny stocks.",
    },
}

# Sector mapping for stocks
SECTORS = {
    "RELIANCE.NS": "Energy", "TCS.NS": "IT", "HDFCBANK.NS": "Banking",
    "INFY.NS": "IT", "ICICIBANK.NS": "Banking", "HINDUNILVR.NS": "FMCG",
    "ITC.NS": "FMCG", "SBIN.NS": "Banking", "BHARTIARTL.NS": "Telecom",
    "KOTAKBANK.NS": "Banking", "LT.NS": "Infrastructure", "AXISBANK.NS": "Banking",
    "ASIANPAINT.NS": "Chemicals", "MARUTI.NS": "Auto", "HCLTECH.NS": "IT",
    "SUNPHARMA.NS": "Pharma", "TITAN.NS": "Consumer", "BAJFINANCE.NS": "Finance",
    "WIPRO.NS": "IT", "ULTRACEMCO.NS": "Cement", "NESTLEIND.NS": "FMCG",
    "POWERGRID.NS": "Power", "NTPC.NS": "Power", "TATAMOTORS.NS": "Auto",
    "JSWSTEEL.NS": "Metals", "ONGC.NS": "Energy", "COALINDIA.NS": "Mining",
    "TECHM.NS": "IT", "INDUSINDBK.NS": "Banking", "CIPLA.NS": "Pharma",
    "DRREDDY.NS": "Pharma", "EICHERMOT.NS": "Auto", "GRASIM.NS": "Cement",
    "DIVISLAB.NS": "Pharma", "BPCL.NS": "Energy", "APOLLOHOSP.NS": "Healthcare",
    "HEROMOTOCO.NS": "Auto", "BRITANNIA.NS": "FMCG", "TATACONSUM.NS": "FMCG",
    "HINDALCO.NS": "Metals", "M&M.NS": "Auto", "BAJAJ-AUTO.NS": "Auto",
    "LTIM.NS": "IT", "TATASTEEL.NS": "Metals", "ADANIENT.NS": "Conglomerate",
    "ADANIPORTS.NS": "Infrastructure", "BAJAJFINSV.NS": "Finance",
    "SBILIFE.NS": "Insurance", "HDFCLIFE.NS": "Insurance",
    "SIEMENS.NS": "Engineering", "HAL.NS": "Defence", "DLF.NS": "Real Estate",
    "ABB.NS": "Engineering", "BANKBARODA.NS": "Banking", "PNB.NS": "Banking",
    "INDIGO.NS": "Aviation", "GODREJCP.NS": "FMCG", "HAVELLS.NS": "Consumer",
    "PIDILITIND.NS": "Chemicals", "DABUR.NS": "FMCG", "AMBUJACEM.NS": "Cement",
    "SHREECEM.NS": "Cement", "TRENT.NS": "Retail", "VEDL.NS": "Metals",
    "IOC.NS": "Energy", "GAIL.NS": "Energy", "MARICO.NS": "FMCG",
    "COLPAL.NS": "FMCG", "BERGEPAINT.NS": "Chemicals", "JUBLFOOD.NS": "Food",
    "MUTHOOTFIN.NS": "Finance", "LUPIN.NS": "Pharma", "TORNTPHARM.NS": "Pharma",
    "AUROPHARMA.NS": "Pharma", "CANBK.NS": "Banking", "IDFCFIRSTB.NS": "Banking",
    "PFC.NS": "Finance", "RECLTD.NS": "Finance", "IRCTC.NS": "Travel",
}
